### ISSUE TITLE
future of this project

### ISSUE THREAD

**Issue by alexpvpmindustry** [movy/robust-jesse-ai#1]
hello!
i have only recently stumbled upon jessie.ai and am interested to learn more of it to do live trading.

two big questions 
- does your implementation require the need for the paid version of jessie.ai?
- will your implementation be opensourced (or what are the current plans?) ?

i am still at the recce phase, to determine if jessie.ai framework is worth the effort.

love to hear more!

**Comment by movy** [comment]
Hello,
Thanks for your interest in this project. To answer your questions:
- yes, in order to ~backtest~ paper trade or live trade paid Jesse subscription is required, there's no way around it. 
- currently I'm in final stages of launching my bot to the market, using Jesse as backbone but with lots of other additions (hence this repo). Once my own bot is stable, I will start populating this repo with certain parts I think worth open sourcing, hopefully within 1-2 months.

**Comment by alexpvpmindustry** [comment]
ok that is cool.
i think u meant paper trade and live trade for the paid subscription.

also, how about totally free alternatives like freqtrade.io?

thanks for the reply!

**Comment by movy** [comment]
Yes, you're correct, I meant paper trade of course. 
Haven't tried freqtrade, but when I was choosing between freqtrade and Jesse, Jesse was more feature complete, allowing to backtest and deploy strategy from within same codebase. Another aspect is scaling. With Jesse I am able to trade 1000+ strategies from a single machine, even though it's not out of the box functionality, but scaling Jesse was not hard. Not sure how freqtrade stands here, but for my trading style running 1000's of routes is crucial.

**Comment by alexpvpmindustry** [comment]
i see.
for now im just testing out, so ill try the free option first.
thanks for the inputs! best of luck!
